### PR TITLE
Update toolchain to 2020-07-27

### PR DESCRIPTION
**Pull request by crawfxrd**
- Specify LTO in the build protfile instead of as a flag to rustc
- Switch from `asm!()` to `llvm_asm!()`
- Update dependencies with build errors
- Update target data layout for newer LLVM releases
- Remove unused compiler-builtins

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
I don't like how much bigger the binary has gotten from, seemingly, just updating the toolchain.

Current master:
```
$ ls -l build/x86_64-efi-pe/boot.*
-rw-rw-r-- 1 tcrawford tcrawford 138884 Oct  7 16:46 build/x86_64-efi-pe/boot.a
-rwxrwxr-x 1 tcrawford tcrawford  69897 Oct  7 16:46 build/x86_64-efi-pe/boot.efi
-rw-rw-r-- 1 tcrawford tcrawford 118592 Oct  7 16:46 build/x86_64-efi-pe/boot.o
```
This branch:
```
$ ls -l build/x86_64-efi-pe/boot.*
-rw-rw-r-- 1 tcrawford tcrawford 417600 Oct  7 16:44 build/x86_64-efi-pe/boot.a
-rwxrwxr-x 1 tcrawford tcrawford  96701 Oct  7 16:44 build/x86_64-efi-pe/boot.efi
-rw-rw-r-- 1 tcrawford tcrawford 373984 Oct  7 16:44 build/x86_64-efi-pe/boot.o
```

**Comment by ids1024** [comment]
In that comparison, `boot.efi` appears to be somewhat smaller. That's what matters, right?

It may be adding some additional symbols of some kind to the object file, but it doesn't matter if those are ultimately optimized out.

**Comment by ids1024** [comment]
It appears both the `.o` and `.a` are unstripped, so it probably doesn't make sense to compare their sizes.

**Comment by ids1024** [comment]
Hm, with `opt-level="z"` it's still `93027`. I wonder what's adding so much to the size...

**Comment by crawfxrd** [comment]
Looking at the extracted archive, `compiler_buitlins`' size has exploded. The `firmware_smmstore` object has only increased by ~300 bytes

**Comment by ids1024** [comment]
I have a guess for (roughly) why it has grown.

* More symbols are being added to compiler-builtins as they are implemented (https://github.com/rust-lang/compiler-builtins#progress)
* Because they are defined there as `pub extern "C"`, and we are building a static library, Rustc probably doesn't omit the unused ones from the resulting `.a`
* The final link with `ld` for some reason isn't removing the symbols.

Passing `--gc-sections` to the final `ld` call seems like a possible solution, but seems to spew "undefined reference" errors.

However, passing it to the `ld -r` call seems to work:

    ld -r --entry _start --gc-sections $(BUILD)/boot/*.o -o $@

That reduces `boot.efi` to 24k. Which sounds good, but it may be hopelessly broken; I still haven't figured out what an smmstore is or how to test it.

Whether or not that works, I'm reasonably confident the `.efi` is ending up with symbols that aren't used.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
